learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL schemes for learning_logs"""

from django.urls import path, re_path
from . import views

app_name = 'learning_logs'
urlpatterns = [
        # Home page
        path('', views.index, name='index'),
        # About page
        path('about', views.about, name='about'),
        # Output all topics.
        re_path(r'^topics/$', views.topics, name='topics'),
        # Page with detailed information on a separate topic.
        re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
        # Page to add a new topic.
        re_path(r'^new_topic/$', views.new_topic, name='new_topic'),
        # Page to add a new entry.
        re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
        # Page to edit entry
        re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines a URL schema for users"""

from django.urls import path, include

from . import views


app_name = 'users'
urlpatterns = [
            #Enable defaullt authorization URL.
            path('', include('django.contrib.auth.urls')),
            #Register page
            path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """Topic that the user is studying."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Returns a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Information received by the user on the topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

        def __str__(self):
            """Returns the string view of the model."""
            return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    """Home page of the Learning Log application"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """ Displays a list of topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """ Display one topic and all its records."""
    topic = Topic.objects.get(id=topic_id)
    # Checking that page belongsto the current user.
    check_topic_owner(topic.owner, request.user)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Determines a new topic."""
    if request.method != 'POST':
        # The data was not sent; Created empty form.
        form = TopicForm()
    else:
        # POST data sent; process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a specific topic."""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic.owner, request.user)

    if request.method != 'POST':
        # No data was sent; an empty forms created
        form = EntryForm()

    else:
        # POST data has been sent; process the data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic.owner, request.user)

    if request.method != 'POST':
        # Original request; the form is filled with
        # the data of the current record.
        form = EntryForm(instance=entry)
    else:
        # POST data has been sent; process the data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def check_topic_owner(topic_created, this_user):
    if topic_created != this_user:
        raise Http404


def about(request):
    """A page with a resume of the creator of this site"""
    return render(request, 'learning_logs/about.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Registers a new user"""
    if request.method != 'POST':
        #Displays an empty registration form.
        form = UserCreationForm()
    else:
        #Processing filled form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Entry and redirection to the homepage.
            login(request, new_user)
            return redirect('learning_logs:index')
    #
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/about.html
{% extends "learning_logs/base.html" %}

{% block title %}
About
{% endblock %}

{% block page_header %}
    <div class='jumbotron'>
        <h1 class="display-3">Hello!</h1>

        <p class="lead"> My name is Dmitry. I study English and program in Python.
           I made this website based on Eric Mattes's book"Python Crash Course".
        </p>

        <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:index' %}"
          role="button">back &raquo;</a>
    
        </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=sevice-width, initial-scale=1,
      shrink-to-fit=on">
    <title>{% block title %}{% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    
  </head>
  <body>
  
    <nav class="navbar navbar-expand-md navbar-light bg-ligth mb-4 border">
      
		<a class="navbar-brand" href="{% url 'learning_logs:index' %}"> 
					Learning Log</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarCollapse" aria-controls="navbarCollapse"
			aria-expended="false" aria-lable="Toggle navigation">
				<span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
		    <ul class="navbar-nav mr-auto">
				<li class="nav-item">
				    <a class="nav-link" href="{% url 'learning_logs:topics' %}">
						Topics</a></li>
				<li class="nav-item">
				    <a class="nav-link" href="{% url 'learning_logs:about' %}">
						About</a></li>
		    
		    </ul>
			
			
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
				    <li class="nav-item">
				        <span class="navbar-text"}">Hello, {{ user.username }}.</span>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:register' %}">Register</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:login' %}">Log in</a>
					</li>
				{% endif %}
			</ul>
		</div>

	</nav>

	<main role="main" class="container">
		<div class="pb-2 mb-2 border-bottom">
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock %}
		</div>		
	</main>
		  
  </body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block title %}
Edit entry
{% endblock %}

{% block page_header %}
  <h3>Edit entry:</h3>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>


  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block title %}
Learning Log
{% endblock %}

{% block page_header %}
    <div class='jumbotron'>
        <h1 class="display-3">Track your learning.</h1>

        <p class="lead">Make your own Learning Log, and keep a list of the topics
          you're learning about. Whenever you learn something new about a
          topic, make an entry summarizing what you've learned.</p>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
          role="button">Register &raquo;</a>
    
        </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block title %}
New entry
{% endblock %}

{% block page_header %}

  <h3>Add a new entry: </h3>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">add entry</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block title %}
New Topic
{% endblock %}

{% block page_header %}
  <h3>Add a new topic:</h3>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submint" class="btn btn-primary">add topic</button>
    {% endbuttons %}
  </form>


{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block title %}
Topic
{% endblock %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
          edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
    {% empty %}
       <p>There are no entries for this topic yet.</p>
    {% endfor %}

{% endblock content  %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block title %}
Topics
{% endblock %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li><h3>
	      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</h3>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block title %}
Registranion
{% endblock title %}

{% block page_header %}
<h2>Registranion</h2>
{% endblock page_header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons%}
      <button name="submit" class="btn btn-primary">register</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>

{% endblock content %}